Traceback (most recent call last):
  File "C:\Users\31633\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\31633\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\31633\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\31633\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\31633\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\31633\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\31633\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\31633\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
landen_selectie = [x for x in hoogste_10_landen_gemtemp.index]
for x in laagste_10_landen_gemtemp.index:
    landen_selectie.append(x)

landen_gesorteerd = df1[df1['Country'].isin(landen_selectie)]

landen_gesorteerd = landen_gesorteerd.sort_values('Total')

plt.figure(figsize=(10, 6))
plt.plot(landen_gesorteerd['Country'], landen_gesorteerd['Total'], marker='o')
plt.xlabel('Land')
plt.ylabel('Totaal aantal immigranten')
plt.title('Totaal aantal immigranten naar Canada op basis van gemiddelde temperatuur')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [7][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m landen_selectie [38;5;241m=[39m [x [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m [43mhoogste_10_landen_gemtemp[49m[38;5;241m.[39mindex]
[0;32m      2[0m [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m laagste_10_landen_gemtemp[38;5;241m.[39mindex:
[0;32m      3[0m     landen_selectie[38;5;241m.[39mappend(x)

[1;31mNameError[0m: name 'hoogste_10_landen_gemtemp' is not defined
NameError: name 'hoogste_10_landen_gemtemp' is not defined

